// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoIhKEUUlvFw-A9ygVhpxArtI2nLLxQtk',
    appId: '1:542043797302:web:ee53009b16ec27562aa597',
    messagingSenderId: '542043797302',
    projectId: 'antrian-online-822b1',
    authDomain: 'antrian-online-822b1.firebaseapp.com',
    storageBucket: 'antrian-online-822b1.firebasestorage.app',
    measurementId: 'G-RCV3PXC1EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABFktmDkQuJOJmsplYpTOqw2510E7yveo',
    appId: '1:542043797302:android:e74f9cbe425d8c0d2aa597',
    messagingSenderId: '542043797302',
    projectId: 'antrian-online-822b1',
    storageBucket: 'antrian-online-822b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs-YCIGFXyyVG-q7Z4QlVSXsJMwHG1SD4',
    appId: '1:542043797302:ios:03ba6db412c8badd2aa597',
    messagingSenderId: '542043797302',
    projectId: 'antrian-online-822b1',
    storageBucket: 'antrian-online-822b1.firebasestorage.app',
    iosBundleId: 'com.example.antrianOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs-YCIGFXyyVG-q7Z4QlVSXsJMwHG1SD4',
    appId: '1:542043797302:ios:03ba6db412c8badd2aa597',
    messagingSenderId: '542043797302',
    projectId: 'antrian-online-822b1',
    storageBucket: 'antrian-online-822b1.firebasestorage.app',
    iosBundleId: 'com.example.antrianOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoIhKEUUlvFw-A9ygVhpxArtI2nLLxQtk',
    appId: '1:542043797302:web:2c3bc2b9115152632aa597',
    messagingSenderId: '542043797302',
    projectId: 'antrian-online-822b1',
    authDomain: 'antrian-online-822b1.firebaseapp.com',
    storageBucket: 'antrian-online-822b1.firebasestorage.app',
    measurementId: 'G-4MSQPN5EPS',
  );

}