// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeskmaQr2Wzy0CAWbPlYu3pwq8mTSN_mE',
    appId: '1:601855261178:web:1c1ddcb3bab98813044c43',
    messagingSenderId: '601855261178',
    projectId: 'antrian-online-253a7',
    authDomain: 'antrian-online-253a7.firebaseapp.com',
    storageBucket: 'antrian-online-253a7.firebasestorage.app',
    measurementId: 'G-KE2471DRM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEaLdowMHqlmNVJv0PRIpaPCLIQUflDvU',
    appId: '1:601855261178:android:c79165b7b4ca1ab7044c43',
    messagingSenderId: '601855261178',
    projectId: 'antrian-online-253a7',
    storageBucket: 'antrian-online-253a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvEkT29TPTWogHezKe97HX7z7DAtCe78o',
    appId: '1:601855261178:ios:1cf04fd52b882b4f044c43',
    messagingSenderId: '601855261178',
    projectId: 'antrian-online-253a7',
    storageBucket: 'antrian-online-253a7.firebasestorage.app',
    iosBundleId: 'com.example.antrianOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvEkT29TPTWogHezKe97HX7z7DAtCe78o',
    appId: '1:601855261178:ios:1cf04fd52b882b4f044c43',
    messagingSenderId: '601855261178',
    projectId: 'antrian-online-253a7',
    storageBucket: 'antrian-online-253a7.firebasestorage.app',
    iosBundleId: 'com.example.antrianOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeskmaQr2Wzy0CAWbPlYu3pwq8mTSN_mE',
    appId: '1:601855261178:web:c10621e6a7e9d6b1044c43',
    messagingSenderId: '601855261178',
    projectId: 'antrian-online-253a7',
    authDomain: 'antrian-online-253a7.firebaseapp.com',
    storageBucket: 'antrian-online-253a7.firebasestorage.app',
    measurementId: 'G-B4RQD9WMPT',
  );
}
